import 'package:sample_app8/models/recipe_model.dart';

List<Recipe> recipeList = <Recipe>[
  const Recipe(
    isFavorite: false,
    //recipeNo: 1,
    //recipeTag: 'Recipe1',
    imgPath: 'assets/recipe_img/kacchib/kacchib3.jpg',
    title: 'Kacchi Biriyani',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
  const Recipe(
    isFavorite: true,
    //recipeNo: 2,
    //recipeTag: 'Recipe2',
    imgPath: 'assets/recipe_img/pizza/pizza3.jpg',
    title: 'Pizza',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
  const Recipe(
    isFavorite: false,
    //recipeNo: 3,
    //recipeTag: 'Recipe3',
    imgPath: 'assets/recipe_img/chickenb/chickenb1.jpg',
    title: 'Chicken Biriyani',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
  const Recipe(
    isFavorite: true,
    // recipeNo: 4,
    // recipeTag: 'Recipe4',
    imgPath: 'assets/recipe_img/roastd/roastd4.jpg',
    title: 'Crisp Roast Duck',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
  const Recipe(
    isFavorite: false,
    //recipeNo: 5,
    //recipeTag: 'Recipe5',
    imgPath: 'assets/recipe_img/applep/applep4.jpg',
    title: 'Apple Pie',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
  const Recipe(
    isFavorite: false,
    //  recipeNo: 6,
    //recipeTag: 'Recipe6',
    imgPath: 'assets/recipe_img/chocolatec/chocolatec3.jpg',
    title: 'Chocolate Cake',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
  const Recipe(
    isFavorite: false,
    // recipeNo: 7,
    // recipeTag: 'Recipe7',
    imgPath: 'assets/recipe_img/borhani/borhani1.jpg',
    title: 'Borhani',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
  const Recipe(
    isFavorite: false,
    //recipeNo: 8,
    //recipeTag: 'Recipe8',
    imgPath: 'assets/recipe_img/chickenm/chickenm2.jpg',
    title: 'Chicken Manchurian',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
  const Recipe(
    isFavorite: true,
    //recipeNo: 9,
    //recipeTag: 'Recipe9',
    imgPath: 'assets/recipe_img/coffee/coffee3.jpg',
    title: 'Coffee',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
  const Recipe(
    isFavorite: false,
    //recipeNo: 10,
    //recipeTag: 'Recipe10',
    imgPath: 'assets/recipe_img/donuts/donuts3.jpg',
    title: 'Donuts',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
  const Recipe(
    isFavorite: true,
    //recipeNo: 11,
    //recipeTag: 'Recipe11',
    imgPath: 'assets/recipe_img/friedrice/rice4.jpg',
    title: 'Fried Rice',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 12,
  //     recipeTag: 'Recipe12',
  //     recipeImgPath: 'assets/recipe_img/chickenfry/chickenf3.jpg',
  //     recipeName: 'Chicken Fry',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 13,
  //     recipeTag: 'Recipe13',
  //     recipeImgPath: 'assets/recipe_img/chineseveg/veg3.jpg',
  //     recipeName: 'Chinese Vegetables',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 14,
  //     recipeTag: 'Recipe14',
  //     recipeImgPath: 'assets/recipe_img/custard/custard2.jpg',
  //     recipeName: 'Custard',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 15,
  //     recipeTag: 'Recipe15',
  //     recipeImgPath: 'assets/recipe_img/pooding/pooding1.jpg',
  //     recipeName: 'Pooding',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 16,
  //     recipeTag: 'Recipe16',
  //     recipeImgPath: 'assets/recipe_img/shorsheilish/ilish2.jpg',
  //     recipeName: 'Shorshe Ilish',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 17,
  //     recipeTag: 'Recipe17',
  //     recipeImgPath: 'assets/recipe_img/kalavuna/kala2.jpg',
  //     recipeName: 'Kala Vuna',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 18,
  //     recipeTag: 'Recipe18',
  //     recipeImgPath: 'assets/recipe_img/beefshashlik/beefsha3.jpg',
  //     recipeName: 'Beef Shashlik',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 19,
  //     recipeTag: 'Recipe19',
  //     recipeImgPath: 'assets/recipe_img/chawmein/chm.jpg',
  //     recipeName: 'chawmein',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 20,
  //     recipeTag: 'Recipe20',
  //     recipeImgPath: 'assets/recipe_img/chickensharma/chknsh2.jpg',
  //     recipeName: 'Chicken Sharma',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 21,
  //     recipeTag: 'Recipe21',
  //     recipeImgPath: 'assets/recipe_img/chingrimalaikari/malai.jpg',
  //     recipeName: 'Chingri Malaikari',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 22,
  //     recipeTag: 'Recipe22',
  //     recipeImgPath: 'assets/recipe_img/chotpoti/chtpti3.jpg',
  //     recipeName: 'Chotpoti',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 23,
  //     recipeTag: 'Recipe23',
  //     recipeImgPath: 'assets/recipe_img/cookies/cks5.jpg',
  //     recipeName: 'Cookies',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 24,
  //     recipeTag: 'Recipe24',
  //     recipeImgPath: 'assets/recipe_img/eggchop/egg3.jpg',
  //     recipeName: 'Egg Chop',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 25,
  //     recipeTag: 'Recipe25',
  //     recipeImgPath: 'assets/recipe_img/fishcurry/fish4.jpg',
  //     recipeName: 'Fish Curry',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 26,
  //     recipeTag: 'Recipe26',
  //     recipeImgPath: 'assets/recipe_img/halim/hlm4.jpg',
  //     recipeName: 'Halim',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 27,
  //     recipeTag: 'Recipe27',
  //     recipeImgPath: 'assets/recipe_img/jilapi/j2.jpg',
  //     recipeName: 'Jilapi',
  //     recipeSubTitle: 'Co & Cookers'),
  // Recipe(
  //     isFavorite: false,
  //     recipeNo: 28,
  //     recipeTag: 'Recipe28',
  //     recipeImgPath: 'assets/recipe_img/masalatea/tea.jpg',
  //     recipeName: 'Masala Tea',
  //     recipeSubTitle: 'Co & Cookers'),
  const Recipe(
    isFavorite: false,
    //recipeNo: 29,
    //recipeTag: 'Recipe29',
    imgPath: 'assets/recipe_img/redvelvet/red3.jpg',
    title: 'Red Velvet',
    subTitle: 'Co & Cookers',
    description: "Recipe 1 description.",
  ),
];
